### ISSUE TITLE
shutdown_timeout does not take effect

### ISSUE THREAD

**Issue by JuchangGit** [warpstreamlabs/bento#106]
我的配置:
```
input:
  stdin:
    scanner:
      lines: {}
    auto_replay_nacks: true
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  stdout:
    codec: lines
  
shutdown_timeout: 5s
```
版本: redpanda-connect_4.30.1_windows_amd64

程序一直没有退出
