### ISSUE TITLE
`schema_registry_decode` Doesn't Decode Keys 

### ISSUE THREAD

**Issue by daviddyball** [warpstreamlabs/bento#141]
Hi All,

We use Avro schema'd keys on some of our messages in Kafka, but it appears that `schema_registry_decode` processor doesn't decode the message key.

Example:

```yaml
input:
  kafka:
    addresses: ["broker:9092"]
    topics: ["topic-1"]
    consumer_group: "my-consumer-group"

pipeline:
  processors:
    - schema_registry_decode:
        url: http://schema-registry:8081
    - mapping: |
        root = metadata("kafka_key").string()

output:
  stdout:
    codec: lines
```

You get a stringified byte-array instead of a deserialized key if the message key is using an Avro/Protobuf/JSONSchema encoded key.

I'm not sure how this can be remedied in the code though as `processors` are given a `Message` struct and it's lost any "Kafka-ness" about it. I guess `metadata("kafka_key")` is still available.

Perhaps it'd be possible to extend `schema_registry_decode` to accept an additional set of fields to attempt to decode?

```yaml
pipelines:
  processors:
    - schema_registry_decode:
        url: http://shema-registry:8081
        decodeHeaderFields:
        - kafka_key
```

Not sure if that's a sane approach though. I think it'd be too much to make `schema_registry_decode` Kafka-aware though, so maybe the above is a good alternative?

Thanks,
DD

**Comment by daviddyball** [comment]
As per [discussion on Slack](https://warpstreamlab-uwt2030.slack.com/archives/C0768UE3NEM/p1730131066844439?thread_ts=1730118813.703459&cid=C0768UE3NEM) it was proposed I use the `branch` processor to decode the `key` schema and I've run some tests and got it working correctly.

For reference here is the code to decode `kafka_key` schemas using Schema Registry and the `branch` processor:

```yaml
input:
  kafka:
    addresses:
      - ${KAFKA_BOOTSTRAP_SERVER}
    consumer_group: ${KAFKA_CONSUMER_GROUP_ID}
pipeline:
  processors:
    - schema_registry_decode:
        url: ${SCHEMA_REGISTRY_URL}
    - branch:
        request_map = |
          root = metadata("kafka_key")
        processors:
          - schema_registry_decode:
              url: ${SCHEMA_REGISTRY_URL}
        result_map = |
          meta kafka_key = this
output:
  processors:
    - mapping: |
        root.key = metadata("kafka_key").string()
        root.message = this.string()
  stdout:
    codec: lines
```

You have to use `switch` statements to handle Kafka tombstone messages though, which makes the config a little more dense, so I've left it out of the example
