### ISSUE TITLE
S3 Processor

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#173]
Consider adding an "S3 Processor" that would function similar to the http processor, where we could replace the message contents with the s3 object data. 

This would be of benefit when using the [streaming-objects-on-upload-with-sqs](https://warpstreamlabs.github.io/bento/docs/components/inputs/aws_s3/#streaming-objects-on-upload-with-sqs) pattern, but you would like to also have access to the SQS message data, or in the case of the 'sqs extended library for large messages' you would like to access s3 on some condition of the SQS message data.

So you would be able to do something like:

```yaml
input:
  aws_sqs:
    url: foo

pipeline:
  processors:
    - branch:
      result_map: |
          root.key = this.sqs.key
          
      processors: 
        - aws_s3:
          bucket: foo_bucket
          key: ${! this.key }

      result_map: |
        root.s3_data = this
```
