### ISSUE TITLE
Secrets Manager components

### ISSUE THREAD

**Issue by GlassPanda** [warpstreamlabs/bento#230]
[Link to discord thread for some context](https://discordapp.com/channels/1130882542451556482/1336727153831710752)

I've run in to an issue where I need to grab secrets from a secret manager (like AWS secrets or Hashicorp Vault) to authenticate with an input, but need to be mindful of when those secrets rotate. I'd like to propose a built-in way to support this, allowing a request to a secrets manager to go out before an input, and then replacing certain fields based on the response. Something like this:
```
input:
  http_client:
    url: http://example.com
    verb: GET
    basic_auth:
      enabled: true
      username: "example"
      password: ${SECRET}

output:
  drop: {}

secrets_manager_resource:
  - label: example_aws
    aws:
      region: "foo"
      endpoint: "bar"
      credentials:
        ...
```

Questions I'm still thinking about:

- Are secrets grabbed on each connect call from the input? Maybe only call once at start and then only call again on errors?
- If not, what happens when a secret is rotated? Is the stream restarted?
- What if there are multiple managers in an environment to grab secrets from? 
- How can this resource alter the component fields before an input is run?

Overall I think this would be a great feature to have in Bento. I'm sure there are many people who do not want to save their secrets anywhere but a manager, especially companies. I'm not very familiar with the project structure yet so not sure what the lift on this would be. Let me know your thoughts!

**Comment by gregfurman** [comment]
Hey! Thanks for opening this. 

So I'm thinking we could instead add AWS secret manager as a [`cache`](https://warpstreamlabs.github.io/bento/docs/components/caches/about) resource -- where perhaps we only support the`get` operations.

There's actually already a Golang cache for AWS secrets that you can see [here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-go.html).

Have added a relevant snippet from those docs:

> The cache policy is Least Recently Used (LRU), so when the cache must discard a secret, it discards the least recently used secret. By default, the cache refreshes secrets every hour. You can configure [how often the secret is refreshed](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-go_CacheConfig.html) in the cache, and you can [hook into the secret retrieval](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-go_CacheHook.html) to add more functionality.

Think this is actually perfect for our use-case. 

So adapting your example to this could look like:

```yaml
input:
  http_client:
    url: http://example.com
    verb: GET
    secret_cache: aws_secret_cache_resource # load in basic_auth.password from here
    basic_auth:
      enabled: true
      username: "example"

output:
  drop: {}

cache_resource:
  - label: aws_secret_cache_resource
    aws_secrets_manager:
      rotate_every: 1h
      region: "foo"
      endpoint: "bar"
      credentials:
        ...

```

**Comment by GlassPanda** [comment]
Thanks for the response!

I do agree on cache being a good fit for this, but had some clarifying questions based on the new example. 

- I had not thought of using a cache resource, would it be able to affect an input before it is run to load in these values? 
- In this example, would a new `secret_cache` field need to be added to every input/output + processors like http?
- Following up the last question, I know outputs and processors can directly use a cache resource already, would you want a split in how its handled between them and inputs? 
- Would the resource hold the details of the path of the secret + which fields in the input need to be loaded?

**Comment by gregfurman** [comment]
> I had not thought of using a cache resource, would it be able to affect an input before it is run to load in these values?

Yeah it would. Similar to our `rate_limit` resource. Custom resources should be loaded in and initialised at `input` time. 

> In this example, would a new secret_cache field need to be added to every input/output + processors like http?

There is a common spec for this. We could always extend it to perhaps include a `secret_cache` field or equivalent.

https://github.com/warpstreamlabs/bento/blob/40f5dd08e6f1d852673c2b7b023fd9ca492e6fb5/public/service/config_http.go#L30-L36

> Following up the last question, I know outputs and processors can directly use a cache resource already, would you want a split in how its handled between them and inputs?

We already do use a `cache` in some `input` components. See [inputs/sftp](https://github.com/warpstreamlabs/bento/blob/40f5dd08e6f1d852673c2b7b023fd9ca492e6fb5/internal/impl/sftp/input.go#L369) as an example.

> Would the resource hold the details of the path of the secret + which fields in the input need to be loaded?

This is a great question. I think there are a lot of different approaches to this one. I've added some options but am open to suggestions! 

#### cache into standardised key

We could allow a `cache` to automatically map a secret to a standardised key like `password`. Then in the resource we could just check if `secret_cache` is enabled/exists and try to load in `password` in the component's initialisation code.

```yaml
input:
  http_client:
    url: http://example.com
    verb: GET
    secret_cache: aws_secret_cache_resource
    basic_auth:
      enabled: true
      username: "example"

cache_resource:
  - label: aws_secret_cache_resource
    aws_secrets_manager:
      retrieve:
        - secret_id: "secret_from_aws"
          key: "password"
          rotate_every: 1h
```

#### new `from_cache` bloblang function

We coul look at creating  a new bloblang function:

```yaml
input:
  http_client:
    url: http://example.com
    verb: GET
    secret_cache: aws_secret_cache_resource
    basic_auth:
      enabled: true
      username: "example"
      password: "from_cache('aws_secret_id')" # new bloblang function
```

#### `password_key` field

Or perhaps even just add a `password_key` field that the component can directly reference:

```yaml
input:
  http_client:
    url: http://example.com
    verb: GET
    secret_cache: aws_secret_cache_resource # load in basic_auth.password from here
    basic_auth:
      enabled: true
      username: "example"
      password_key: "aws_secret_id" # check for password_key in config
```

#### `input.secret_cache` object

Same approach as above but defines which secret info we want to retrieve from inside a `secret_cache` object

```yaml
input:
  http_client:
    url: http://example.com
    verb: GET
    secret_cache:
        name: aws_secret_cache_resource
        secret_id: "aws_secret_id"
        key: "password"
    basic_auth:
      enabled: true
      username: "example"
```
