### ISSUE TITLE
bento tries to login to AWS even when there is no processor, input, or output that requires it

### ISSUE THREAD

**Issue by enzo-cappa** [warpstreamlabs/bento#239]
Hello! thanks for all the hard work. Describing my problem below.

# Scenario

I'm testing a very simple pattern. I want to :
- start with an HTTP input
- write a row to a sqlite DB based on the input
- return the request
- write to a file

This is the configuration:

```yaml
input:
  http_server:
    path: /enrich
    allowed_verbs:
      - POST
    sync_response:
      headers:
        Content-Type: application/json

pipeline:
  processors:
    - label: sqlinsert
      sql_insert:
        driver: sqlite
        dsn: file:./tmp/database.db
        table: contacts
        columns: [ firstname, lastname ]
        args_mapping: |
          root = [
            this.firstname,
            this.lastname,
          ]
        credentials: {}
    - sync_response: {}

output:
  file:
    path: ./tmp/data_output.txt # No default (required)
    codec: lines
```

# Error

When trying to start it, I get the following error:

```text
INFO Running main config from specified file       @service=bento bento_version=1.5.0 path=bento_config.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=bento
ERRO Service closing due to: failed to init processor 'sqlinsert' path root.pipeline.processors.0: profile "default" is configured to use SSO but is missing required configuration: sso_region, sso_account_id, sso_role_name  @service=bento
make: *** [bento.run] Error 1
```

Which means that Bento is trying to connect to AWS, even when it's not needed at all. Prior to this I also got this error:

```text
failed to load shared config file, /Users/xxx/.aws/credentials, read all: read /Users/xxx/.aws/credentials: is a directory
```

Then I removed the folder, and since then I get the other error.

# Expected behaviour

I should be able to use sqlite locally without a connection to AWS.

Thanks!
