### ISSUE TITLE
Output sql_raw, prepared statement does not exist err

### ISSUE THREAD

**Issue by nakastoev** [warpstreamlabs/bento#243]
My config looks like:
```
input:
    sql_raw:
      driver: postgres
      dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?sslmode=disable
      query: "SELECT id FROM partner where dt_update < NOW()::date order by id"

  output:
    sql_raw:
      driver: postgres
      dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?sslmode=disable
      query: "UPDATE partner SET dt_update = NOW() where id = $1"
      args_mapping: |
          root = [
            this.id,
          ]
```

When I run it (in docker if that matters), i see some `level=error msg="Failed to send message to sql_raw: pq: unnamed prepared statement does not exist" @service=bento label="" path=root.output`  logs, however, records in db are modified correctly
