### ISSUE TITLE
How to configure multiple Pub/Sub topics as input and switch output based on topic name?

### ISSUE THREAD

**Issue by ibadi-id** [warpstreamlabs/bento#250]
I'm using Bento to process messages from multiple Google Pub/Sub topics and want to route them to different outputs based on the topic name.

My Goal:
Subscribe to multiple topics in gcp_pubsub.input.
Dynamically switch the output based on the topic name.
I checked the documentation and found that it only mentions metadata such as:

gcp_pubsub_publish_time_unix – The time at which the message was published to the topic.
gcp_pubsub_delivery_attempt – When dead lettering is enabled, this indicates the number of times Pub/Sub has attempted to deliver a message.

Is there a way to access the topic name in a switch statement?

```

input:
  broker:
    inputs:
      - gcp_pubsub:
            project: "my-project"
            subscription: "topic-a-subscription"
            create_subscription:
              enabled: false
              topic: "topic-a"
      - gcp_pubsub:
            project: "my-project"
            subscription: "topic-b-subscription"
            create_subscription:
              enabled: false
              topic: "topic-b"


output:
  switch:
    cases:
      - check: meta("gcp_pubsub_topic") == "topic-a"
        output:
          stdout: {}
      - check: meta("gcp_pubsub_topic") == "topic-b"
        output:
          amqp_0_9:
            urls: ["amqp://guest:guest@localhost:5672/"]
            exchange: "exchange-b"

```

**Comment by jem-davies** [comment]
You can associate processors with a particular input - [shown here](https://warpstreamlabs.github.io/bento/docs/components/inputs/about).

So you could do something like this: 

```yaml

input:
  broker:
    inputs:
      - gcp_pubsub:
            project: "my-project"
            subscription: "topic-a-subscription"
            create_subscription:
              enabled: false
              topic: "topic-a"
        
        processors: 
          - mapping: |
              meta gcp_pubsub_topic = "topic-a"

      - gcp_pubsub:
            project: "my-project"
            subscription: "topic-b-subscription"
            create_subscription:
              enabled: false
              topic: "topic-b"

        processors: 
          - mapping: |
              meta gcp_pubsub_topic = "topic-b"

output:
  switch:
    cases:
      - check: meta("gcp_pubsub_topic") == "topic-a"
        output:
          stdout: {}
      - check: meta("gcp_pubsub_topic") == "topic-b"
        output:
          amqp_0_9:
            urls: ["amqp://guest:guest@localhost:5672/"]
            exchange: "exchange-b"
```

You would have to check the output to see if you needed to remove the metadata in the output processors.
