### ISSUE TITLE
Processor template lint error

### ISSUE THREAD

**Issue by henrikschristensen** [warpstreamlabs/bento#294]
I am having some difficulties getting processor templates working.
I have this template

```yaml
name: ppp
type: processor

fields:
  - name: somevalue
    type: string

mapping: |
  root.bloblang = """
    root.value = this.somevalue
    """
```

And this stream

```yaml
input:
  generate:
    count: 1
    mapping: 'root = {}'

pipeline:
  processors:
    - ppp:
      somevalue: "hello world"

output:
  stdout:
    codec: lines
```

Running this results in a lint error
NFO Running main config from specified file       @service=bento bento_version=1.5.2 path=stream.yaml
ERRO Config lint error                             @service=bento lint="stream.yaml(8,1) expected object value, got !!null"
ERRO Config lint error                             @service=bento lint="stream.yaml(9,1) field somevalue is invalid when the component type is ppp (processor)"
ERRO Shutting down due to linter errors, to prevent shutdown run Bento with --chilled  @service=bento

What am I doing wrong?

**Comment by jem-davies** [comment]
Hey, it's just the level of indentation of the line `somevalue: "hello world"`

```yaml
input:
  generate:
    count: 1
    mapping: 'root = {}'

pipeline:
  processors:
    - ppp:
        somevalue: "hello world"

output:
  stdout:
    codec: lines
```

should work
