### ISSUE TITLE
Include Stream support for Dynamo Streams

### ISSUE THREAD

**Issue by denis-fwd** [warpstreamlabs/bento#303]
### Description

Currently, Bento provides support Kinesis streams, but does not support integration with DynamoDB Streams. 

When using this configuration, I encounter a parsing error:

```yaml
input:
  # Read from a DynamoDB stream
  aws_kinesis:
    streams:
      - arn:aws:dynamodb:us-east-1:$AWS_ACCOUNT_ID:table/events-table/stream/2024-03-20T18:19:47.921
    region: us-east-1
    credentials:
      profile: development-account
output:
  stdout: {}
```

```sh
level=info msg="Running main config from specified file" @service=bento bento_version=1.5.2 path=./config/bento.config.yaml
level=info msg="Listening for HTTP requests at: http://0.0.0.0:4195" @service=bento
level=error msg="Service closing due to: failed to init input <no label> path root.input: stream '/2024-03-20T18:19:47.921' is invalid, only one shard should be specified and the same stream can be listed multiple times, e.g. use `foo:0,foo:1` not `foo:0:1`" @service=bento
```

### Proposed Implementation

```yaml
input:
  # Read from a DynamoDB stream
  dynamo_stream:
    streams:
      - arn:aws:dynamodb:us-east-1:$AWS_ACCOUNT_ID:table/events-table/stream/2024-03-20T18:19:47.921
    region: us-east-1
    credentials: {}
output:
  stdout: {}
```
