### ISSUE TITLE
Add interpolation to logger static_fields

### ISSUE THREAD

**Issue by webfrank** [warpstreamlabs/bento#328]
Hi, it would be useful to have interpolation for logger static_fields, this would help to add information to logs, for example:

```yaml
logger:
  level: INFO
  format: json
  static_fields:
    tenant: ${! @tenant }
```

and inside a stream:

```yaml
...
mapping: meta tenant = "xxx"
...
```

This way a logging query could filter on tenant field (if inside a multi tenant application)
