### ISSUE TITLE
Buffer won't after output recovers

### ISSUE THREAD

**Issue by hsphere-florent** [warpstreamlabs/bento#329]
I'm using sqlite buffer and http_client output to write into Influxdb http api. 

when my output destination becomes unavailable (ex. influxdb server down): 
`context deadline exceeded (Client.Timeout exceeded while awaiting headers) `

In that time, the buffer is correctly filled up, but when my output destination becomes available again (ex. influxdb server up again) nothing happens, the buffer still grow while ingesting messages, and don't pass them to the output. 

If i restart bento, then the buffer messages are passed to the output. 

...but i need to restart bento... 

Here is my config (running bento 1.7):

```
buffer:
  sqlite:
    path: /bento-data/bento1-buffer.db

output:
  retry:
    max_retries: 0
    backoff:
      initial_interval: 100ms
      max_interval: 2s
      max_elapsed_time: 0s
    output:
      resource: influxdb2
```
