### ISSUE TITLE
sql_insert: unsupported go type: Number

### ISSUE THREAD

**Issue by JuchangGit** [warpstreamlabs/bento#330]
配置1 number2_generate.yaml  ：（运行成功）// configuration - run successfully
```
http:
  enabled: false
  
input:
  generate:
    mapping: root = {"TID":"1001", "AGE":12, "F1":12.66}
    count: 1

output:
  sql_insert:
    driver: oracle
    dsn: oracle://TEST:testpwd@127.0.0.1:1521/HQPDBTEST
    table: TEST2
    columns: [ TID, AGE, F1 ]
    args_mapping: |
      root = [ this.TID, this.AGE, this.F1 ]
    max_in_flight: 1
    init_statement: TRUNCATE TABLE TEST2
    batching:
      count: 500
      period: 100ms
    
logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
  static_fields:
    '@service': bento
    
rate_limit_resources:
  - label: rate_limit1
    local:
      count: 1
      interval: 1s
```
```
bento -c number2_generate.yaml
```

![Image](https://github.com/user-attachments/assets/760782e6-6d2d-465b-81bb-55478c7c88ac)

模拟接口配置 number_httpserver1.yaml  // http_server configuration (simulative socket configuration) 
```
input:
  http_server:
    path: /xq
    allowed_verbs: [POST]
    sync_response:
      status: ${! (@status).string() }
      headers:
        Content-Type: application/json
                    
pipeline:
  processors:
    - mapping: |
        root = {"AGE":12,"F1":12.66,"TID":"1001"}
        meta status = "200"             
    - catch:
      - mapping: |
          meta status = "500"
    - sync_response: {}
    
output:
  stdout:
    codec: lines
  processors:
    - mapping: |
        root = {"time": "["+ now().ts_format("2006-01-02 15:04:05").ts_strptime("%Y-%m-%d %H:%M:%S") + "]", "data": this, "meta": @}
```
配置2 number2.yaml （运行失败）// configuration 2 failed 
```
http:
  enabled: false
  
input:
  read_until:
    check: count("messages") >= 1
    input:
      http_client:
        url: 'http://127.0.0.1:4195/xq'
        verb: POST
        rate_limit: rate_limit1
        timeout: 90s
        headers:
          Content-Type: application/json

output:
  sql_insert:
    driver: oracle
    dsn: oracle://TEST:testpwd@127.0.0.1:1521/HQPDBTEST
    table: TEST2
    columns: [ TID, AGE, F1 ]
    args_mapping: |
      root = [ this.TID, this.AGE, this.F1 ]
    max_in_flight: 1
    init_statement: TRUNCATE TABLE TEST2
    batching:
      count: 500
      period: 100ms
    
logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
  static_fields:
    '@service': bento
    
rate_limit_resources:
  - label: rate_limit1
    local:
      count: 1
      interval: 1s
```
```
bento -c number2.yaml
```

![Image](https://github.com/user-attachments/assets/e06a852b-3b70-47fe-bda7-c45a20a4e9fc)

**Comment by jem-davies** [comment]
taking a look

**Comment by jem-davies** [comment]
Ok so I have been able to replicate this issue too ...

**Comment by jem-davies** [comment]
So a quick fix for this can be made in the config: 

```yaml
output:
  sql_insert:
    driver: oracle
    dsn: oracle://TEST:testpwd@127.0.0.1:1521/HQPDBTEST
    table: TEST2
    columns: [ TID, AGE, F1 ]
    args_mapping: |
      root = [ this.TID, this.AGE.number(), this.F1.number() ]
    max_in_flight: 1
    init_statement: TRUNCATE TABLE TEST2
    batching:
      count: 500
      period: 100ms
```

When you use the http_client input - you get a type of json.Number for AGE and F1 - but you can type cast them to golang's primitive float64 / int64 using the bloblang method .number().

This should only affect Oracle and Clickhouse because it doesn't use the github.com/Masterminds/squirrel sql statement builder...
