### ISSUE TITLE
Add options to nats object store components

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#338]
The `nats_kv` input component has the following fields: 

```yaml
    ignore_deletes: false
    include_history: false
    meta_only: false
```

We could add these to the `nats_object_store` components (or just the input)
