### ISSUE TITLE
CSV Scanner and Input Lint Rule

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#357]
```
input:
  file:
    paths: [./tmp/csv_expected_headers/data.csv]
    scanner:
      csv:
        parse_header_row: false
        expected_headers: [first_sname, last_name, age]
        expected_number_of_fields: 3
```

Current behaviour of the above config will not check or parse the first row as headers, `parse_header_row: false` that is false but perhaps would be good to add a lint rule to avoid setting `parse_header_row: false` and setting `expected_headers`
