### ISSUE TITLE
Unit test output_batches will pass tests with random words as "matcher" types

### ISSUE THREAD

**Issue by bcatarinocs** [warpstreamlabs/bento#382]
Due to a typo, I tried to use `bloglang` as a matcher (instead of `bloblang`:

```
    output_batches:
      - - bloglang: 'false'
```

When running the test, I got:
`Test 'config.yaml' succeeded`.

Should bento test fail when a non-existing matcher is used? It definitely would give some "compile-time" safety to the tool.

**Comment by jem-davies** [comment]
https://warpstreamlab-uwt2030.slack.com/archives/C0768UE3NEM/p1750850648609889

**Comment by jem-davies** [comment]
Seems that I am not getting the previously documented behaviour: 

```yaml
input:
  stdin: {}

pipeline:
  processors:
    - mapping: root = content().uppercase()

output:
  stdout: {}

tests:
  - name: example test
    target_processors: '/pipeline/processors'
    input_batch:
      - content: 'example content'
    output_batches:
      - - bloblang: true
```

```sh
bento test ./config.yaml
```

```
Test 'config.yaml' failed

Failures:

--- config.yaml ---

Lint: (17,1) field bloglang not recognised
```
