### ISSUE TITLE
Add Individual Message ack/nack support for Bento Lambda

### ISSUE THREAD

**Issue by ethanae** [warpstreamlabs/bento#59]
When dealing with message batches coming from an AWS event source (in my case SQS) I am unable to express that messages that failed processing are returned to the queue and messages that succeeded processing are deleted from the queue. 

It would seem that Bento on Lambda on the output level always either deletes all messages from the SQS queue or makes them all visible again on the SQS queue. 

In short, what would be great is if:
1. successful messages are deleted from the queue
2. failed messages are made visible again

Below are my two attempts at expressing the desired behaviour but without success. 

1. https://gist.github.com/ethanae/9cd6d229a36630d1155158e2128d2d97
2. https://gist.github.com/ethanae/7d8ddaf0939eae56a3125a6c1859752b

Discord discussion: https://discord.com/channels/1130882542451556482/1255151084218089482

**Comment by gregfurman** [comment]
Thanks for raising this here, Ethan! Looks like there are some updates coming in from upstream that _may_ contain a fix for this message batching issue. I'm going to see if this helps: https://github.com/warpstreamlabs/bento/pull/56/commits/776e827564452c97215657900f97501e787bf2a6

**Comment by ethanae** [comment]
Thanks, @gregfurman. 

Just to clarify, my Lambds-SQS event source mapping does specify [ReportBatchItemFailures](https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting). If that's of any help.

**Comment by gregfurman** [comment]
There's this snippet in the **Note** in the [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting) you linked:
> - If your function throws an exception, the entire batch is considered a complete failure.

There is also this from the [bento serverless docs](https://warpstreamlabs.github.io/bento/docs/guides/serverless/lambda#processing-errors):
> ... the handler will fail if messages have encountered an uncaught error during execution. However, in the meantime it is possible to configure your output to use the new [reject output](https://warpstreamlabs.github.io/bento/docs/components/outputs/reject) in order to trigger a handler error on processor errors:

The default behaviour here in `bento-lambda` is that a lambda exception will be thrown if an error is encountered. Also (as I understand now) `reject` will also explicitly trigger an exception. 

So long as an exception is being thrown, it appears the entire batch will be reprocessed. In lieu of a better solution, I'm thinking there could be a way to use a [`catch`](https://warpstreamlabs.github.io/bento/docs/configuration/error_handling/#logging-errors)to prevent this. Otherwise, going to think on the best way going forward with a solution.

**Comment by ethanae** [comment]
> There's this snippet in the **Note** in the [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html#services-sqs-batchfailurereporting) you linked:
> 
> > * If your function throws an exception, the entire batch is considered a complete failure.
> 
> There is also this from the [bento serverless docs](https://warpstreamlabs.github.io/bento/docs/guides/serverless/lambda#processing-errors):
> 
> > ... the handler will fail if messages have encountered an uncaught error during execution. However, in the meantime it is possible to configure your output to use the new [reject output](https://warpstreamlabs.github.io/bento/docs/components/outputs/reject) in order to trigger a handler error on processor errors:
> 
> The default behaviour here in `bento-lambda` is that a lambda exception will be thrown if an error is encountered. Also (as I understand now) `reject` will also explicitly trigger an exception.
> 
> So long as an exception is being thrown, it appears the entire batch will be reprocessed. I'm thinking there could be a way to use a [`catch`](https://warpstreamlabs.github.io/bento/docs/configuration/error_handling/#logging-errors) as a temporary workaround to prevent this. Otherwise, going to think on the best way going forward with a solution.

I am interested in trying out a solution with `catch`. I'll attempt to reduce all message results at the end of my workflow into a batch item failure list. 👍

**Comment by ethanae** [comment]
Hey @gregfurman 

You were spot-on. I achieved this with a top-level `catch`, an `archive` (back into `json_array` after processing messages individually), and a final `mapping` to build the `{ batchItemFailures }`. I guess we don't need any changes for this? Perhaps adding it to the documentation _may_ beneficial.

Full config:

```
pipeline:
  processors:
    - mapping: root = this.Records
    - unarchive:
        format: json_array
    - switch:
        - check: this.body == "Hello from SQS!"
          processors:
            - mapping: throw("the bads") # force an error
        - processors:
            - label: log_message
              log:
                level: DEBUG
                message: 'successfully processed'
    - catch:
        - label: log_error
          log:
            level: DEBUG
            message: 'error'
            fields_mapping: root.error = this
        - mapping: |
            root.error = "true"
            root.messageId = this.messageId
            root.error_msg = error()

    - archive:
        format: json_array
    - mapping: |
        root.batchItemFailures = this.filter(record -> record.error == "true").map_each(r -> {"itemIdentifier":r.messageId})

output:
  sync_response: {}

logger:
  level: 'DEBUG'
  format: json
  add_timestamp: true

```
