### ISSUE TITLE
Connection status incorrect postgre sql_insert

### ISSUE THREAD

**Issue by emmanuelbertho** [warpstreamlabs/bento#70]
Hello,

I noticed a bug when using sql_insert with postgres as an output in streams mode.
When I put fake connection parameters for postgres the /stats endpoint for my stream displays that the connection is up tough it is not.

Logs : 

`2024-07-10 09:49:57 {"@service":"bento","label":"","level":"warning","msg":"Failed to execute init_statement: dial tcp: lookup myhost on 127.0.0.11:53: no such host","path":"root.output","stream":"Emmanuel"}
2024-07-10 09:49:57 {"@service":"bento","label":"","level":"info","msg":"Output type sql_insert is now active","path":"root.output","stream":"Emmanuel"}`

Stream : 

`{
  "active": true,
  "uptime": 6.814057709,
  "uptime_str": "6.814057788s",
  "config": {
    "buffer": {
      "none": { }
    },
    "input": {
      "redis_streams": {
        "body_key": "data",
        "streams": [
          "value-change-Emmanuel"
        ],
        "url": "redis://redis:6379"
      }
    },
    "output": {
      "sql_insert": {
        "args_mapping": "[ this.timestamp, this.data.string() ]",
        "columns": [
          "timestamp",
          "data"
        ],
        "driver": "postgres",
        "dsn": "postgres://fakeuser:fakepasswd@myhost:1234/?database=fakedb&sslmode=disable",
        "init_statement": "CREATE TABLE IF NOT EXISTS aa (\n   timestamp TIMESTAMPTZ NOT NULL,\n   data jsonb NOT NULL);\nSELECT create_hypertable('aa', by_range('timestamp'));",
        "table": "aa"
      }
    },
    "pipeline": {
      "processors": [
        {
          "mapping": "\r\n                root.data = this\r\n                root.data.\"\" = deleted()\r\n                root.timestamp = now()"
        }
      ]
    }
  }
}`

Stats : 

`{
  "input_connection_failed{label=\"\",path=\"root.input\",stream=\"Emmanuel\"}": 0,
  "input_connection_lost{label=\"\",path=\"root.input\",stream=\"Emmanuel\"}": 0,
  "input_connection_up{label=\"\",path=\"root.input\",stream=\"Emmanuel\"}": 1,
  "input_latency_ns{label=\"\",path=\"root.input\",stream=\"Emmanuel\"}": {
    "p50": 0,
    "p90": 0,
    "p99": 0
  },
  "input_received{label=\"\",path=\"root.input\",stream=\"Emmanuel\"}": 0,
  "output_batch_sent{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 0,
  "output_connection_failed{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 0,
  "output_connection_lost{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 0,
  "output_connection_up{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 1,
  "output_error{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 0,
  "output_latency_ns{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": {
    "p50": 0,
    "p90": 0,
    "p99": 0
  },
  "output_sent{label=\"\",path=\"root.output\",stream=\"Emmanuel\"}": 0,
  "processor_batch_received{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": 0,
  "processor_batch_sent{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": 0,
  "processor_error{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": 0,
  "processor_latency_ns{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": {
    "p50": 0,
    "p90": 0,
    "p99": 0
  },
  "processor_received{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": 0,
  "processor_sent{label=\"\",path=\"root.pipeline.processors.0\",stream=\"Emmanuel\"}": 0,
  "uptime_ns": 123757643066
}`

**Comment by emmanuelbertho** [comment]
Ok great ! Sorry my Golang knowledges are not enough to do a fix myself :(

**Comment by gregfurman** [comment]
Have been giving this some more though.

The [output metric docs](https://warpstreamlabs.github.io/bento/docs/components/metrics/about/#outputs) say the following about the `output_connection_up` metric:

> `output_connection_up`: For continuous stream based outputs represents a count of the number of the times the output has successfully established a connection to the target sink. For poll based outputs that do not retain an active connection this value will increment once.

With the caveat:

> The behaviour of connection metrics may differ based on output type due to certain libraries and protocols obfuscating the concept of a single connection.

_Technically_ the Golang SQL package opens a connection pool and opens/closes connection to the DB as needed and I'm wondering if we need actually need to reconsider how this is tracked/managed by bento.

I agree that that metric indicating things are up is confusing. I'm unsure whether checking if the DB can be communicated with at `Connect()` time is desirable since it means we can't "lazily load" the ouput sinks.

Will think on this some more and decide if it's necessary to fix. Maybe adding a `disable_lazy_loading` option could be a viable workaround while still not introducing a breaking change.

**Comment by emmanuelbertho** [comment]
Ok makes sense. 
My goal is to check if the connection parameters I am using are correct when I create a stream but if it is not possible I can probably find a workaround.

**Comment by gregfurman** [comment]
It's probably a bit of a stretch but you could just do a simple check against both your DBs in the input as follows:

```yaml
  sql_raw:
    driver: postgres
    dsn: postgres://postgres:admin@localhost:5432/?database=postgres&sslmode=disable
    query: SELECT 1;
```

This should fail if the `SELECT 1;` query is unable to execute. So you could do:

```yaml
input:
  broker:
    inputs:
      - sql_raw:
          driver: postgres
          dsn: postgres://postgres:admin@localhost:5432/?database=postgres&sslmode=disable
          query: SELECT 1;
        processors:
          - mapping: root = deleted()
      - sql_raw:
          driver: postgres
          dsn: postgres://postgres:admin@localhost:5432/?database=timescale&sslmode=disable
          query: SELECT 1;
        processors:
          - mapping: root = deleted()
      - resource: foo # run the resource you actually care about here
```
