### ISSUE TITLE
Input/Output multiple collections

### ISSUE THREAD

**Issue by Bluetreeteem** [warpstreamlabs/bento#99]
How can I import/export multiple collections when using the MongoDB input type. Here is my code below.

```yaml
input:
  mongodb:
    url: "#####"
    database: "db_1"
    collection: "collection1"  # Collections to export

    query: |
        root._id = { "$exists": true }  # Query to select documents

pipeline:
  processors:
    - mapping: 
        root = content()  

output:
  mongodb:
    url: "#####"  
    database: "db_2"
    collection: "collection1"  
    operation: "insert-one"
    document_map: |
        root = this
    write_concern:
      w: "majority" 
```

**Comment by gregfurman** [comment]
Hey. Unfortunately there is no native functionality in Bento to select multiple collections at once. I'd give a look at [input brokering](https://warpstreamlabs.github.io/bento/docs/components/inputs/about/#brokering) to read multiple inputs in conjunction with [output switching/multiplexing](https://warpstreamlabs.github.io/bento/docs/components/outputs/switch/) to handle this one. 

So, a potential approach you could take is:
- Define multiple `mongodb` inputs using a `broker`
- Attach some [metadata](https://warpstreamlabs.github.io/bento/docs/configuration/metadata/) to each message indicating the `collection` name using `mapping` or `bloblang` (still in the `input` section)
- Use a switch case, switching on `metadata` names i.e 

```yaml
output:
  switch:
    cases:
      - check: '@mongodb_collection == "collection1"'
        output:
          mongodb: # set config, namely collection to "collection1"

      - check: '@mongodb_collection == "collection2"'
        output:
          mongodb: # same here, for "collection2"
 ```

I think this raises a good point that we should consider [adding string interpolation support](https://warpstreamlabs.github.io/bento/docs/configuration/interpolation/) to these mongodb fields.

**Comment by gregfurman** [comment]
I actually just gave this another look. It appears the `output` component for `mongodb` does support string interpolation, but the docs do not reflect this.

The above `output` can instead look like:

```yaml
output:
   mongodb: # set config, namely collection to "collection1"
      url: "#####"
      database: "db_2"
      collection: ${! metadata("mongodb_collection") } # reference the metadata here
```
